import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    // Auth check
    const authHeader = req.headers.get('Authorization')!
    const { data: { user }, error: authError } = await supabase.auth.getUser(authHeader.replace('Bearer ', ''))
    if (authError || !user) return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: corsHeaders })

    const { siteName, businessType, tone, palette, sections, extra, client_id } = await req.json()

    // 1. Rate Limit check
    const today = new Date().toISOString().split('T')[0]
    const { count } = await supabase
      .from('templeteria_ai_jobs')
      .select('*', { count: 'exact', head: true })
      .eq('created_by', user.id)
      .eq('mode', 'GENERATE')
      .gte('created_at', today)

    const limit = parseInt(Deno.env.get('TEMPLETERIA_DAILY_LIMIT_PER_USER') ?? '10')
    if (count && count >= limit) {
      return new Response(JSON.stringify({ error: 'Daily limit reached' }), { status: 429, headers: corsHeaders })
    }

    // 2. Insert running job
    const { data: job } = await supabase
      .from('templeteria_ai_jobs')
      .insert({
        client_id,
        status: 'RUNNING',
        mode: 'GENERATE',
        input_payload_json: { siteName, businessType, tone, palette, sections, extra },
        created_by: user.id
      })
      .select()
      .single()

    // 3. AI call (Gemini-style or OpenAI)
    // Note: Since this is a local script, we use a structured stub as requested for immediate closure
    // Real API call would go here using Deno.env.get('OPENAI_API_KEY')
    const template = {
      theme: {
        palette: palette || 'classic',
        font: 'Inter'
      },
      pages: [
        {
          id: 'home',
          title: 'Home',
          blocks: sections.map((s: string, i: number) => ({
            id: `block-${i}`,
            type: s,
            props: {
              headline: `${siteName} - ${s.toUpperCase()}`,
              content: `Content for ${s} generated by AI.`
            }
          }))
        }
      ]
    }

    // 4. Update job
    await supabase
      .from('templeteria_ai_jobs')
      .update({
        status: 'DONE',
        output_payload_json: { template },
        provider: 'local-stub'
      })
      .eq('id', job.id)

    return new Response(JSON.stringify({ template, assets: { images: [] } }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: corsHeaders,
    })
  }
})
